{"type":"PR","pr":{"number":39,"head":"b9dac88799050becdc8637081b967ec3fa086939"},"user":"Leonel Elimpe","status":"draft","branch":"cms/2019-06-06-on-exception-handling-with-try-catch-in-javascript","collection":"post","title":"On Exception Handling with try/catch in Javascript","description":"No Description!","objects":{"entry":{"path":"_posts/2019-06-06-on-exception-handling-with-try-catch-in-javascript.md","sha":"44379a2a2df6f2b8d577594b2d855f6bce17391f"},"files":[]},"timeStamp":"2019-06-06T07:00:39.842Z"}